
(()=>{let enabled=false,epoch=0,applying=false,dirty=false,lastSent='',timer=null;let noteSequence=0,noteEvents=[],remoteNotesReady=false,seenNoteEvents=new Set();let lastAppliedLayout='',remoteFrame=0,remoteAngle=null;const originalSave=save;save=function(){if(applying||!enabled)return;dirty=true;};
function snapshot(){let actor=S?.turn??0;if(cashUI&&cashUI.to!==-1&&paymentPairInvolved(cashUI.to,-1))actor=cashUI.to;else if(cashUI&&cashUI.to!==-1&&cardPaymentsPending()){const v=account(S.turn,cashUI.to);if(v&&v.target!==v.net&&(v.target-v.net>0?v.a:v.b)===cashUI.to)actor=cashUI.to;}return {noteEvents,state:S?JSON.parse(JSON.stringify(S)):null,cash:cashUI,unfolded:[...unfolded],selected,busy:!!busy,transit,angle:activeWheelSpin?.angle??S?.wheelAngle,actor,modal:{open:modal.open,html:modal.innerHTML},property:{open:!document.getElementById('property-float').hidden,tile:document.getElementById('property-float').dataset.tile}};}
function publish(force=false){if(!enabled||applying)return;const value=snapshot(),encoded=JSON.stringify(value);if(force||encoded!==lastSent){lastSent=encoded;parent.postMessage({type:'game-snapshot',epoch,snapshot:value},location.origin)}}
const originalNoteAnimation=animateNoteTransfer;
animateNoteTransfer=function(args){const permitted=enabled&&cashUI&&validTransferPair(args.from,args.to)&&args.source?.isConnected&&(args.from===-1||(S.players[args.from]?.wallet?.[args.d]||0)>0);const result=originalNoteAnimation(args);if(permitted){noteEvents.push({id:epoch+':'+(++noteSequence),from:args.from,to:args.to,d:args.d});noteEvents=noteEvents.slice(-40);dirty=true;publish()}return result};
function prepareRemoteNotes(value){const events=value.noteEvents||[];if(!remoteNotesReady){remoteNotesReady=true;events.forEach(e=>seenNoteEvents.add(e.id));return []}return events.filter(e=>!seenNoteEvents.has(e.id)).map(e=>{seenNoteEvents.add(e.id);const source=document.querySelector('.wallet-money .note[data-owner="'+e.from+'"][data-value="'+e.d+'"]');return {...e,origin:source?.getBoundingClientRect(),ghost:source?.cloneNode(true)}})}
function showRemoteNotes(events){for(const e of events){if(!e.ghost||!e.origin)continue;const arrival=document.querySelector('.wallet-money .note[data-owner="'+e.to+'"][data-value="'+e.d+'"]');const area=walletArea(e.to);const fallback=arrival?.getBoundingClientRect()||area?.getBoundingClientRect();if(!fallback)continue;const g=e.ghost;g.classList.add('note-flight');g.classList.remove('note-arriving');g.removeAttribute('data-owner');Object.assign(g.style,{left:e.origin.left+'px',top:e.origin.top+'px',width:e.origin.width+'px',height:e.origin.height+'px',visibility:'visible',opacity:'1'});document.body.appendChild(g);flyNote(g,arrival,e.origin,fallback).finally(()=>g.remove())}}
function cancelRemoteWheel(){if(remoteFrame)cancelAnimationFrame(remoteFrame);remoteFrame=0;}
function remoteWheel(angle,smooth){if(angle==null)return;cancelRemoteWheel();if(!smooth||remoteAngle==null){remoteAngle=angle;paintWheel(angle);return}const origin=remoteAngle,start=performance.now();function tick(now){const progress=Math.min(1,(now-start)/120);remoteAngle=origin+(angle-origin)*progress;paintWheel(remoteAngle);if(progress<1)remoteFrame=requestAnimationFrame(tick);else remoteFrame=0}remoteFrame=requestAnimationFrame(tick)}
function layoutKey(value){const state=value.state?{...value.state}:null;if(state)delete state.wheelAngle;const {angle,...rest}=value;return JSON.stringify({...rest,state})}
function apply(value){if(!value)return;const flights=prepareRemoteNotes(value);const key=layoutKey(value);if(key===lastAppliedLayout&&S){remoteWheel(value.angle,!!value.busy&&!enabled);busy=enabled?false:!!value.busy;return}lastAppliedLayout=key;applying=true;try{if(activeWheelSpin){cancelAnimationFrame(activeWheelSpin.frame);activeWheelSpin=null}const float=document.getElementById('property-float'),inspected=!float.hidden?Number(float.dataset.tile):null;const scroll=captureWalletScroll();transit=value.transit;selected=null;if(enabled){cashUI=value.cash;unfolded=new Set(value.unfolded||[])}busy=false;const incoming=value.state?JSON.parse(JSON.stringify(value.state)):null;if(S&&incoming){for(const key of Object.keys(S))if(!(key in incoming))delete S[key];Object.assign(S,incoming);}else S=incoming;if(S){render(true);remoteWheel(value.angle,!!value.busy&&!enabled);if(inspected!=null&&S.props[inspected])openProperty(inspected);else hideProperty();restoreWalletScroll(scroll);}else setup();if(enabled&&value.modal?.open){modal.innerHTML=value.modal.html;if(!modal.open)modal.showModal()}else if(modal.open)modal.close();busy=enabled?false:!!value.busy;showRemoteNotes(flights);}finally{applying=false}}
const oldOpenCash=openCash,oldSwitchReceiver=switchReceiver,oldCloseCash=closeCash,oldDismiss=canDismissCashOutside;
openCash=function(...args){if(enabled)return oldOpenCash(...args);if(!S)return;cashUI={from:onlineSeat,to:-1};renderWallets()};
switchReceiver=function(id,...args){if(enabled)return oldSwitchReceiver(id,...args);id=Number(id);if(id===onlineSeat)return;cashUI={from:onlineSeat,to:id};renderWallets()};
closeCash=function(){if(enabled)return oldCloseCash();cashUI=null;renderWallets()};
canDismissCashOutside=function(){return enabled?oldDismiss():!!cashUI};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data.type!=='room-control')return;const next=e.data;const gained=next.enabled&&!enabled;const epochChanged=next.epoch!==epoch;enabled=!!next.enabled;onlineControl=enabled;onlineSeat=next.seat??onlineSeat;document.body.classList.toggle('online-spectator',!enabled);epoch=next.epoch;if(!enabled&&activeWheelSpin){cancelAnimationFrame(activeWheelSpin.frame);activeWheelSpin=null}if(next.snapshot&&(!enabled||gained||epochChanged))apply(next.snapshot);if(gained&&next.players&&!S){document.getElementById('count').value=next.players.length;setupNames();next.players.forEach((p,i)=>{document.getElementById('name'+i).value=p.name;document.getElementById('color'+i).value=p.color});startGame();}if(gained){noteEvents=[];remoteNotesReady=false;seenNoteEvents.clear();cancelRemoteWheel();lastAppliedLayout='';busy=false;lastSent='';dirty=true;publish(true)}});
function viewingTarget(target){return !!target.closest?.('.deed-card,.cash-stack,#property-float .float-close,.receiver-identity,[onclick="toggleCash()"],[onclick="closeCash()"]')}
for(const type of ['pointerdown','pointerup','click','keydown','change','input','dragstart','drop'])document.addEventListener(type,e=>{const view=viewingTarget(e.target);if(!enabled){if(!view&&!['pointerdown','pointerup'].includes(type)){e.preventDefault();e.stopImmediatePropagation()}return}if(!view){dirty=true;setTimeout(()=>publish(),0)}},true);
setInterval(()=>{if(enabled&&(dirty||busy)){dirty=false;publish()}},100);
parent.postMessage({type:'game-ready'},location.origin);
})();
