(()=>{
let authoritative=null;let rememberedReceiver=-1;const priorSwitch=switchReceiver;switchReceiver=function(...args){const result=priorSwitch(...args);if(cashUI)rememberedReceiver=cashUI.to;return result};
let resetHistory=false,orderStamp='',orderPosting=false;let enabled=false,epoch=0,applying=false,financeVersion=0,lastSent='',dirty=false,actionPending=0,pendingSnapshot=null,localNotes=[],seen=new Set(),remoteFrame=0,remoteAngle=0,remoteSpinning=false,rpcId=0;const requests=new Map();
function rpc(data){return new Promise((resolve,reject)=>{const id=++rpcId;requests.set(id,{resolve,reject});parent.postMessage({type:'game-action',id,data},location.origin);setTimeout(()=>{if(requests.has(id)){requests.delete(id);reject(Error('连接超时，请重新连接'))}},15000)})}
save=function(){if(!applying&&enabled&&!actionPending)dirty=true;};canActLocally=function(){return onlineSeat!=null;};setViewedPlayer=function(){};
function actor(){return S?.phase==='contest'?S.contest.players[S.contest.results.length]:S?.phase==='free'?S.free.who:S?.turn??0}
function snapshot(){S.bankExchanges??={};if(S.exchange)S.bankExchanges[onlineSeat]=S.exchange;else delete S.bankExchanges[onlineSeat];return {state:JSON.parse(JSON.stringify({...S,undoNotes:[],cashReceiver:null,exchange:null})),resetHistory,author:onlineSeat,financeVersion,busy:false,actor:actor()};}
function publish(){if(!enabled||applying||actionPending||busy||!S)return;const value=snapshot(),encoded=JSON.stringify(value);if(encoded!==lastSent){lastSent=encoded;parent.postMessage({type:'game-snapshot',epoch,snapshot:value},location.origin)}dirty=false;resetHistory=false;}
// Rebase unpublished game changes onto a newer server cash update.
// A landing debt or cancellation must survive an unrelated concurrent gift.
function financial(value){
 if(!value?.state)return;
 financeVersion=value.financeVersion||0;
 const incoming=JSON.parse(JSON.stringify(value.state)),base=enabled&&authoritative;
 if(S&&base){
  incoming.players.forEach((p,i)=>{const local=S.players[i],old=base.players[i];if(!local||!old)return;p.cash+=local.cash-old.cash;for(const d of NOTES)p.wallet[d]=(p.wallet[d]||0)+(local.wallet[d]||0)-(old.wallet[d]||0);if(JSON.stringify(local.deedOrder)!==JSON.stringify(old.deedOrder))p.deedOrder=local.deedOrder;});
  for(const key of new Set([...Object.keys(S.props),...Object.keys(base.props)])){if(JSON.stringify(S.props[key])!==JSON.stringify(base.props[key])){if(S.props[key])incoming.props[key]=JSON.parse(JSON.stringify(S.props[key]));else delete incoming.props[key];}}
  incoming.accounts??={};
  for(const key of new Set([...Object.keys(S.accounts||{}),...Object.keys(base.accounts||{})])){const local=S.accounts?.[key],old=base.accounts?.[key],target=(local?.target||0)-(old?.target||0),net=(local?.net||0)-(old?.net||0);if(target||net){const entry=incoming.accounts[key]??={...local,target:0,net:0};entry.target+=target;entry.net+=net;}}
  const signature=n=>JSON.stringify([n.from,n.to,n.amount,n.reason]),changes=new Map();for(const n of base.notices||[])changes.set(signature(n),(changes.get(signature(n))||0)-1);for(const n of S.notices||[])changes.set(signature(n),(changes.get(signature(n))||0)+1);
  incoming.notices=(incoming.notices||[]).filter(n=>{const k=signature(n),count=changes.get(k)||0;if(count<0){changes.set(k,count+1);return false;}return true;});for(const n of S.notices||[]){const k=signature(n),count=changes.get(k)||0;if(count>0){incoming.notices.push({...n});changes.set(k,count-1);}}
  incoming.giftBalances??={};for(const k of new Set([...Object.keys(S.giftBalances||{}),...Object.keys(base.giftBalances||{})]))incoming.giftBalances[k]=(incoming.giftBalances[k]||0)+(S.giftBalances?.[k]||0)-(base.giftBalances?.[k]||0);
  if(S.purchase&&incoming.purchase&&S.purchase.tile===incoming.purchase.tile)incoming.purchase.paid+=(S.purchase.paid||0)-(base.purchase?.paid||0);
 }
 authoritative=JSON.parse(JSON.stringify(value.state));
 if(S){incoming.players.forEach((p,i)=>{if(S.players[i]){if(p.deedOrder)S.players[i].deedOrder=[...p.deedOrder];S.players[i].wallet=p.wallet;S.players[i].cash=p.cash;}});S.props=incoming.props;S.accounts=incoming.accounts||{};S.giftBalances=incoming.giftBalances||{};S.bankExchanges=incoming.bankExchanges||{};S.exchange=S.bankExchanges[onlineSeat]||null;S.notices=incoming.notices||[];if(S.purchase&&incoming.purchase)S.purchase.paid=incoming.purchase.paid;syncNotices();}
 if(enabled){dirty=true;lastSent='';}
}
function cancelRemote(){if(remoteFrame)cancelAnimationFrame(remoteFrame);remoteFrame=0;}
function remoteStart(e){if(e.who===onlineSeat)return;cancelRemote();remoteSpinning=true;remoteAngle=e.startAngle;let last=performance.now();function tick(now){remoteAngle+=now-last;last=now;paintWheel(remoteAngle);remoteFrame=requestAnimationFrame(tick)}remoteFrame=requestAnimationFrame(tick);}
function remoteStop(value){if(!remoteSpinning)return;cancelRemote();remoteSpinning=false;const target=value.state.wheelAngle;if(target==null)return;const delta=((target-remoteAngle)%360+360)%360+360,origin=remoteAngle,start=performance.now();function tick(now){const t=Math.min(1,(now-start)/700);paintWheel(origin+delta*(1-Math.pow(1-t,3)));if(t<1)remoteFrame=requestAnimationFrame(tick);else remoteFrame=0}remoteFrame=requestAnimationFrame(tick);}
function arrival(e){if(e.to!==onlineSeat||e.actor===onlineSeat)return;const area=walletArea(onlineSeat);if(!area)return;const ghost=document.createElement('div');ghost.innerHTML=noteHTML(e.d,onlineSeat);const note=ghost.firstElementChild;note.classList.add('note-flight');note.removeAttribute('data-owner');const dest=area.querySelector('.note-grid>.note[data-value="'+e.d+'"]')||area.querySelector('.cash-stack')||area;const r=dest.getBoundingClientRect();Object.assign(note.style,{left:(r.left+(r.width-96)/2)+'px',top:(r.top-45)+'px',width:'96px',height:'62px'});document.body.append(note);note.animate([{opacity:0,transform:'translateY(-20px) scale(.8)'},{opacity:1,transform:'translateY(45px) scale(1)'}],{duration:400,easing:'ease-out'}).finished.finally(()=>{note.remove();dest.animate([{filter:'brightness(1.15)'},{filter:'brightness(1)'}],{duration:220})});}
function apply(value,events=[],force=false){if(!value)return;if(enabled&&S&&!force&&!actionPending){if(value.financeVersion>financeVersion)financial(value);else authoritative=JSON.parse(JSON.stringify(value.state));localNotes=JSON.parse(JSON.stringify(value.state.onlineUndo?(value.state.onlineUndo[onlineSeat]||[]):localNotes));S.undoNotes=localNotes;if(!busy){applying=true;render(true);applying=false;events.forEach(arrival);}return;}if(actionPending||busy){pendingSnapshot={value,events:[...(pendingSnapshot?.events||[]),...events]};if(!actionPending&&value.financeVersion>financeVersion)financial(value);return;}applying=true;try{const float=document.getElementById('property-float'),tile=!float.hidden?Number(float.dataset.tile):null,scroll=captureWalletScroll();S=JSON.parse(JSON.stringify(value.state));authoritative=JSON.parse(JSON.stringify(value.state));S.cashReceiver=rememberedReceiver;if(modal.open&&modal.querySelector('#count'))closeDialog();financeVersion=value.financeVersion||0;S.exchange=S.bankExchanges?.[onlineSeat]||null;localNotes=JSON.parse(JSON.stringify(S.onlineUndo?.[onlineSeat]||[]));S.undoNotes=localNotes;selected=null;transit=null;render(true);if(tile!=null&&S.props[tile]?.owner===onlineSeat)openProperty(tile);restoreWalletScroll(scroll);events.forEach(arrival);}finally{applying=false}}
const originalRenderWalk=renderWalk;renderWalk=function(){document.querySelectorAll('.end-turn-button').forEach(button=>button.remove());originalRenderWalk();const button=document.getElementById('mainAction'),end=document.querySelector('.end-turn-button');if(spinRequest&&button){button.disabled=true;button.textContent='连接中…';}if(!enabled){if(button)button.disabled=true;if(end)end.disabled=true;}if(S?.phase==='contest'&&button){const next=S.players[actor()];button.style.background=playerColor(next);button.textContent=activeWheelSpin?(activeWheelSpin.braking?'减速中…':'停止转盘'):'转转盘';}};
const priorDetail=renderDetail;renderDetail=function(){if(S?.phase==='contest'&&onlineSeat!==S.contest.who){if(actor()===onlineSeat){actionPanel('<h2>请转转盘</h2><p class="detail-body">轮到你完成这次特殊转盘，无需走棋。</p>');return;}document.getElementById('event-panel').hidden=true;return;}if(S?.phase==='free'&&S.free.who===onlineSeat){showFree();return;}priorDetail();};
const priorClose=closeCash;closeCash=function(){if(S.startReward?.who!=null&&S.startReward.who!==onlineSeat){const reward=S.startReward;S.startReward=null;try{return priorClose()}finally{S.startReward=reward}}return priorClose()};
const oldPurchaseControls=purchaseControls;purchaseControls=function(){return S.purchase?.who===onlineSeat?oldPurchaseControls():''};
let spinRequest=false;const oldRoll=roll;roll=async function(){if(!enabled||busy||spinRequest)return;spinRequest=true;const button=document.getElementById('mainAction');if(button){button.disabled=true;button.textContent='连接中…';}try{const response=await rpc({kind:'spin'});const run=oldRoll();if(activeWheelSpin)activeWheelSpin.serverValue=response.value;spinRequest=false;return await run;}catch(e){notify(e.message)}finally{spinRequest=false;if(!busy)renderWalk()}};
const oldStop=stopWheelSpin;stopWheelSpin=function(){const spin=activeWheelSpin;if(!spin||spin.braking)return;oldStop();if(spin.serverValue){const current=((spin.brakeAngle%360)+360)%360,target=-(spin.serverValue-1)*30;let distance=((target-current)%360+360)%360;while(distance<300)distance+=360;spin.duration=2*distance/spin.speed;}};

let paymentQueue=Promise.resolve(),latestPayment=null;const oldAnimate=animateNoteTransfer;
animateNoteTransfer=async function(args){if(!cashUI||!validTransferPair(args.from,args.to))return;const selectedCash={...cashUI};actionPending++;const request=paymentQueue.catch(()=>{}).then(()=>rpc({kind:args.undo?'undo':'money',from:args.from,to:args.to,d:args.d}));paymentQueue=request;try{const response=await request;latestPayment=response;financeVersion=response.financeVersion;applying=true;S=JSON.parse(JSON.stringify(response.before.state));authoritative=JSON.parse(JSON.stringify(response.before.state));S.cashReceiver=rememberedReceiver;S.exchange=S.bankExchanges?.[onlineSeat]||null;S.undoNotes=localNotes;cashUI=selectedCash;applying=false;if(!args.undo)localNotes.push({...response.undo,book:response.before.state.accounts||{},gifts:response.before.state.giftBalances||{},exchange:response.before.state.bankExchanges?.[onlineSeat]||null,purchase:response.before.state.purchase});await oldAnimate(args);}catch(e){notify(e.message);}finally{applying=false;actionPending--;if(!actionPending){const response=latestPayment;latestPayment=null;if(response){S=JSON.parse(JSON.stringify(response.snapshot.state));authoritative=JSON.parse(JSON.stringify(response.snapshot.state));S.cashReceiver=rememberedReceiver;S.exchange=S.bankExchanges?.[onlineSeat]||null;localNotes=JSON.parse(JSON.stringify(S.onlineUndo?.[onlineSeat]||[]));S.undoNotes=localNotes;}if(pendingSnapshot){const next=pendingSnapshot;pendingSnapshot=null;apply(next.value,next.events);}else render(true);if(response&&!args.undo&&response.event.official&&!S.purchase){const v=account(response.event.from,response.event.to);if(v&&v.target===v.net){S.manualCash=true;if(!cashUI&&S.startReward?.confirmed&&S.startReward.who===onlineSeat)cashUI={from:onlineSeat,to:-1};if(cashUI)closeCash();}}dirty=enabled;publish();}}};
undoVoluntary=function(){const t=localNotes.at(-1);if(!t||!cashUI||pairKey(t.from,t.to)!==pairKey(cashUI.from,cashUI.to))return;const source=walletArea(t.to)?.querySelector(t.to===-1?'.bank-stack .note[data-value="'+t.d+'"]:last-child':'.note-grid>.note[data-value="'+t.d+'"]');if(source){localNotes.pop();S.undoNotes=localNotes;refreshUndoControls();animateNoteTransfer({from:t.to,to:t.from,d:t.d,source,undo:true})}};
const turnActions=['buy','build','confirmPurchase','cancelPurchase','endTurn','executeCard','drawOne','doFree','acknowledgeSkip','confirmStartReward'];for(const name of turnActions){const prior=window[name];if(prior)window[name]=function(...args){if(!enabled)return;return prior(...args)}}
assetAction=async function(i,sell){if(S.props[i]?.owner!==onlineSeat||busy)return;try{const response=await rpc({kind:'asset',tile:i,sell:!!sell});financial(response.snapshot);S.props=JSON.parse(JSON.stringify(response.snapshot.state.props));render(true);openProperty(i);openCash(onlineSeat,-1);dirty=enabled;}catch(e){notify(e.message)}};
const priorRestore=restore;restore=function(state){resetHistory=true;localNotes=[];state.onlineUndo={};state.undoNotes=[];state.bankExchanges??={};return priorRestore(state)};newGame=function(){parent.location.href='/';};document.addEventListener('change',e=>{if(e.target.id==='import'&&!enabled){e.preventDefault();e.stopImmediatePropagation();notify('请由当前操作者读取存档。')}},true);const oldSelect=selectTile;selectTile=function(i,inspect=false){if(inspect)return oldSelect(i,true);if(enabled)return oldSelect(i,false)};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;const msg=e.data;if(msg.type==='game-action-result'){const pending=requests.get(msg.id);if(pending){requests.delete(msg.id);msg.error?pending.reject(Error(msg.error)):pending.resolve(msg.result)}return}if(msg.type!=='room-control')return;const gained=msg.enabled&&!enabled;enabled=!!msg.enabled;onlineControl=true;onlineSeat=msg.seat??onlineSeat;epoch=msg.epoch;let events=[];for(const event of msg.events||[]){if(seen.has(event.id))continue;seen.add(event.id);if(event.kind==='spin-cancel'){cancelRemote();remoteSpinning=false;}else if(event.kind==='spin')remoteStart(event);else if(event.kind==='spin-result'){if(msg.snapshot)remoteStop(msg.snapshot);}else if(event.kind==='money')events.push(event)}if(msg.snapshot){if(!(enabled&&busy&&msg.snapshot.financeVersion===financeVersion))apply(msg.snapshot,events,gained)}if(gained&&msg.players&&!S){applying=true;document.getElementById('count').value=msg.players.length;setupNames();msg.players.forEach((p,i)=>{document.getElementById('name'+i).value=p.name;document.getElementById('color'+i).value=p.color});startGame();applying=false;dirty=true;publish();}if(S&&!busy)renderWalk();});
document.addEventListener('click',e=>{const action=e.target.closest('[onclick]')?.getAttribute('onclick')||'';if(!enabled&&/^(mainAction|endPlayerTurn|buy|build|executeCard|drawOne|doFree|confirmPurchase|cancelPurchase|acknowledgeSkip|confirmStartReward)\(/.test(action)){e.preventDefault();e.stopImmediatePropagation()}},true);
setInterval(()=>{if(!busy&&!actionPending&&pendingSnapshot){const next=pendingSnapshot;pendingSnapshot=null;apply(next.value,next.events)}if(S&&onlineSeat!=null&&!actionPending){const order=S.players[onlineSeat]?.deedOrder||[],stamp=JSON.stringify(order);if(!orderStamp)orderStamp=stamp;else if(stamp!==orderStamp&&!orderPosting){orderPosting=true;orderStamp=stamp;rpc({kind:'order',order}).catch(e=>notify(e.message)).finally(()=>orderPosting=false);}}if(dirty)publish()},80);parent.postMessage({type:'game-ready'},location.origin);
})();