
(()=>{let enabled=false,epoch=0,applying=false,dirty=false,lastSent='',timer=null;const originalSave=save;save=function(){if(applying||!enabled)return;dirty=true;};
function snapshot(){let actor=S?.turn??0;if(cashUI&&cashUI.to!==-1&&paymentPairInvolved(cashUI.to,-1))actor=cashUI.to;return {state:S?JSON.parse(JSON.stringify(S)):null,cash:cashUI,unfolded:[...unfolded],selected,busy:!!busy,transit,angle:activeWheelSpin?.angle??S?.wheelAngle,actor,modal:{open:modal.open,html:modal.innerHTML},property:{open:!document.getElementById('property-float').hidden,tile:document.getElementById('property-float').dataset.tile}};}
function publish(force=false){if(!enabled||applying)return;const value=snapshot(),encoded=JSON.stringify(value);if(force||encoded!==lastSent){lastSent=encoded;parent.postMessage({type:'game-snapshot',epoch,snapshot:value},location.origin)}}
function apply(value){if(!value)return;applying=true;try{if(activeWheelSpin){cancelAnimationFrame(activeWheelSpin.frame);activeWheelSpin=null}transit=value.transit;selected=value.selected;cashUI=value.cash;unfolded=new Set(value.unfolded||[]);busy=false;const incoming=value.state?JSON.parse(JSON.stringify(value.state)):null;if(S&&incoming){for(const key of Object.keys(S))if(!(key in incoming))delete S[key];Object.assign(S,incoming);}else S=incoming;if(S){render(true);if(value.angle!=null)paintWheel(value.angle);if(value.property?.open)openProperty(Number(value.property.tile));else hideProperty();}else setup();if(value.modal?.open){modal.innerHTML=value.modal.html;if(!modal.open)modal.showModal()}else if(modal.open)modal.close();busy=enabled?false:!!value.busy;}finally{applying=false}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data.type!=='room-control')return;const next=e.data;const gained=next.enabled&&!enabled;const epochChanged=next.epoch!==epoch;enabled=!!next.enabled;epoch=next.epoch;if(!enabled&&activeWheelSpin){cancelAnimationFrame(activeWheelSpin.frame);activeWheelSpin=null}if(next.snapshot&&(!enabled||gained||epochChanged))apply(next.snapshot);if(gained&&next.players&&!S){document.getElementById('count').value=next.players.length;setupNames();next.players.forEach((p,i)=>{document.getElementById('name'+i).value=p.name;document.getElementById('color'+i).value=p.color});startGame();}if(gained){busy=false;lastSent='';dirty=true;publish(true)}});
for(const type of ['pointerdown','pointerup','click','keydown','change','input','dragstart','drop'])document.addEventListener(type,e=>{if(!enabled){e.preventDefault();e.stopImmediatePropagation();return}dirty=true;setTimeout(()=>publish(),0)},true);
setInterval(()=>{if(enabled&&(dirty||busy)){dirty=false;publish()}},100);
parent.postMessage({type:'game-ready'},location.origin);
})();
