
const $=id=>document.getElementById(id),roomCode=new URLSearchParams(location.search).get('room');let identity=null,room=null,frameReady=false,connected=false,posting=false,queued=null,lastRevision=-1,currentEpoch=0;
if(roomCode){$('welcome').textContent='输入名字，加入朋友的房间。';$('enter').textContent='加入房间'}
function error(text){$('error').textContent=text||''}
async function api(action,data={},auth=true){const query=auth?'?room='+identity.code+'&id='+identity.id:'';const response=await fetch('/api/'+action+query,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error||'连接失败');return value}
function configureFrame(snapshot){if(!frameReady||!room)return;$('game').contentWindow.postMessage({type:'room-control',seat:room.members.find(m=>m.id===identity.id)?.seat,enabled:connected&&room.controller===identity.id,epoch:room.epoch,snapshot,events:room.events,players:room.started?room.members.slice().sort((a,b)=>a.seat-b.seat):null},location.origin)}
function draw(){if(!room)return;drawWaiting();const controller=room.members.find(m=>m.id===room.controller),mine=room.controller===identity.id;currentEpoch=room.epoch;$('status').textContent=connected?(mine?'轮到你操作':(controller?.name||'朋友')+'正在操作'):'连接中，请稍候';$('shield').style.display='none';$('watching').textContent=connected?(controller?.name||'朋友')+'正在操作':'重新连接中';const options=room.snapshot?.state?.players||Array.from({length:4},(_,i)=>({name:'玩家 '+(i+1)}));$('seat').innerHTML='';for(let i=0;i<options.length;i++){const option=document.createElement('option');option.value=i;option.textContent=options[i].name;const used=room.members.find(m=>m.seat===i&&m.id!==identity.id);option.disabled=!!used;if(used)option.textContent+='（'+used.name+'）';$('seat').append(option)}const member=room.members.find(m=>m.id===identity.id);$('seat').value=member?.seat??'';
$('members').replaceChildren();for(const m of room.members){const button=document.createElement('button');button.textContent=m.name+(m.online?'':' · 离线');button.className=(m.id===identity.id?'mine ':'') +'';button.disabled=!m.online||m.id===room.controller||(!mine&&identity.id!==room.host)||room.snapshot?.busy;button.disabled=true;button.onclick=null;$('members').append(button)}}
function receive(data){const previous=room,changed=!previous||previous.epoch!==data.epoch;room=data;connected=true;draw();if(data.revision!==lastRevision||changed||JSON.stringify(previous?.events)!==JSON.stringify(data.events)){lastRevision=data.revision;if(changed)queued=null;configureFrame(data.snapshot)}else configureFrame(undefined)}
let entering=false;
function storedIdentity(code){if(!code)return null;for(const storage of [sessionStorage,localStorage]){try{const raw=storage.getItem('world-trip-room-'+code);if(raw){const value=JSON.parse(raw);if(value.code===code&&typeof value.id==='string')return value}}catch{}}return null}
function keepIdentity(value){for(const storage of [sessionStorage,localStorage])try{storage.setItem('world-trip-room-'+value.code,JSON.stringify(value))}catch{}}
async function enter(){if(entering)return;entering=true;$('enter').disabled=true;try{const name=$('name').value.trim()||'朋友';const saved=storedIdentity(roomCode);if(saved){identity=saved;await api('resume');}else{identity=roomCode?await fetch('/api/join?room='+roomCode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}):await api('create',{name},false);}keepIdentity(identity);
history.replaceState(null,'','?room='+identity.code);$('lobby').hidden=true;$('top').hidden=false;const stream=new EventSource('/api/events?room='+identity.code+'&id='+identity.id);stream.onmessage=e=>receive(JSON.parse(e.data));stream.onerror=()=>{connected=false;draw();configureFrame(undefined);error('连接中断，正在重连。')};stream.onopen=()=>error('');}catch(e){error(e.message);entering=false;$('enter').disabled=false;}}
$('enter').onclick=enter;$('seat').onchange=()=>api('seat',{seat:Number($('seat').value)}).catch(e=>{error(e.message);draw()});$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);error('链接已复制')}catch{prompt('复制这个房间链接',location.href)}};
async function flush(){if(posting||!queued||!connected||room?.controller!==identity.id)return;posting=true;const item=queued;queued=null;try{await api('snapshot',{snapshot:item.snapshot,epoch:item.epoch});}catch(e){error(e.message);configureFrame(room?.snapshot);setTimeout(()=>flush(),1000);return;}finally{posting=false;if(queued&&connected)setTimeout(()=>flush(),120)}}
window.addEventListener('message',async e=>{if(e.origin!==location.origin||e.source!==$('game').contentWindow)return;const msg=e.data;if(msg.type==='game-action'){if(msg.data.kind==='spin'){const until=Date.now()+12000;while(connected&&(posting||queued)&&Date.now()<until){await flush();await new Promise(resolve=>setTimeout(resolve,20));}}api('action',msg.data).then(result=>$('game').contentWindow.postMessage({type:'game-action-result',id:msg.id,result},location.origin)).catch(e=>$('game').contentWindow.postMessage({type:'game-action-result',id:msg.id,error:e.message},location.origin));return}if(msg.type==='game-ready'){frameReady=true;configureFrame(room?.snapshot)}if(msg.type==='game-snapshot'&&connected&&room?.controller===identity.id&&msg.epoch===room.epoch){queued={snapshot:msg.snapshot,epoch:msg.epoch};flush()}});

const lobbyColors=['#3478ce','#d84b48','#e7bb35','#399560'];let draftColor=null,profileStamp='',gameLoaded=false;
function drawWaiting(){const mine=room.members.find(m=>m.id===identity.id);$('waiting').hidden=room.started;$('stage').hidden=!room.started;$('members').hidden=!room.started;if(room.started){if(!gameLoaded){gameLoaded=true;$('game').src='/game'}return}const stamp=mine.name+'|'+mine.color;if(profileStamp!==stamp){profileStamp=stamp;$('playerName').value=mine.name;draftColor=mine.color} $('roster').replaceChildren();for(const m of room.members){const row=document.createElement('div');row.className='room-player';row.style.background=m.color;const initial=document.createElement('span');initial.className='initial';initial.textContent=[...m.name][0]||'?';const name=document.createElement('span');name.textContent=m.name+(m.id===room.host?' · 房主':'');const ready=document.createElement('span');ready.className='ready-state';ready.textContent=!m.online?'离线':m.ready?'已准备':'未准备';row.append(initial,name,ready);$('roster').append(row)}$('colors').replaceChildren();for(const c of lobbyColors){const button=document.createElement('button');button.style.background=c;button.className=draftColor===c?'selected':'';button.setAttribute('aria-label',['蓝色','红色','黄色','绿色'][lobbyColors.indexOf(c)]);button.onclick=()=>updateProfile(c,false);$('colors').append(button)}$('ready').textContent=mine.ready?'取消准备':'准备';$('start').hidden=identity.id!==room.host;const duplicated=new Set(room.members.map(m=>m.color)).size!==room.members.length;$('start').disabled=room.members.length<2||room.members.some(m=>!m.online||!m.ready)||duplicated;$('colorNotice').textContent=duplicated?'颜色重复，请有人换一个颜色。':''}
let profileQueue=Promise.resolve();
async function updateProfile(color=draftColor,ready=false){draftColor=color;const data={name:$('playerName').value.trim(),color,ready};try{profileQueue=profileQueue.catch(()=>{}).then(()=>api('profile',data));await profileQueue;error('')}catch(e){error(e.message)}}
$('playerName').onchange=()=>updateProfile();$('ready').onclick=()=>updateProfile(draftColor,!room.members.find(m=>m.id===identity.id).ready);$('start').onclick=()=>api('start').catch(e=>error(e.message));

if(storedIdentity(roomCode)){ $('welcome').textContent='正在恢复原来的角色…';enter();}
