
const $=id=>document.getElementById(id),roomCode=new URLSearchParams(location.search).get('room');let identity=null,room=null,frameReady=false,connected=false,posting=false,queued=null,lastRevision=-1,currentEpoch=0;
if(roomCode){$('welcome').textContent='输入名字，加入朋友的房间。';$('enter').textContent='加入房间'}
function error(text){$('error').textContent=text||''}
async function api(action,data={},auth=true){const query=auth?'?room='+identity.code+'&id='+identity.id:'';const response=await fetch('/api/'+action+query,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error||'连接失败');return value}
function configureFrame(snapshot){if(!frameReady||!room)return;$('game').contentWindow.postMessage({type:'room-control',enabled:connected&&room.controller===identity.id,epoch:room.epoch,snapshot},location.origin)}
function draw(){if(!room)return;const controller=room.members.find(m=>m.id===room.controller),mine=room.controller===identity.id;currentEpoch=room.epoch;$('status').textContent=connected?(mine?'轮到你操作':(controller?.name||'朋友')+'正在操作'):'连接中，请稍候';$('shield').style.display=mine&&connected?'none':'block';$('watching').textContent=connected?(controller?.name||'朋友')+'正在操作':'重新连接中';$('request').disabled=!connected||mine;const options=room.snapshot?.state?.players||Array.from({length:4},(_,i)=>({name:'玩家 '+(i+1)}));$('seat').innerHTML='';for(let i=0;i<options.length;i++){const option=document.createElement('option');option.value=i;option.textContent=options[i].name;const used=room.members.find(m=>m.seat===i&&m.id!==identity.id);option.disabled=!!used;if(used)option.textContent+='（'+used.name+'）';$('seat').append(option)}const member=room.members.find(m=>m.id===identity.id);$('seat').value=member?.seat??'';
$('members').replaceChildren();for(const m of room.members){const button=document.createElement('button');button.textContent=m.name+(m.online?'':' · 离线')+(room.requests.includes(m.id)?' · 请求操作':'');button.className=(m.id===identity.id?'mine ':'')+(room.requests.includes(m.id)?'requested':'');button.disabled=!m.online||m.id===room.controller||(!mine&&identity.id!==room.host)||room.snapshot?.busy;button.onclick=async()=>{try{await api('handoff',{target:m.id})}catch(e){error(e.message)}};$('members').append(button)}}
function receive(data){const previous=room,changed=!previous||previous.epoch!==data.epoch;room=data;connected=true;draw();if(data.revision!==lastRevision||changed){lastRevision=data.revision;if(changed)queued=null;configureFrame(data.snapshot)}else configureFrame(undefined)}
async function enter(){try{const name=$('name').value.trim()||'朋友';const key='world-trip-room-'+roomCode;let saved=roomCode?sessionStorage.getItem(key):null;if(saved){identity=JSON.parse(saved)}else{identity=roomCode?await fetch('/api/join?room='+roomCode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}):await api('create',{name},false);sessionStorage.setItem('world-trip-room-'+identity.code,JSON.stringify(identity))}
history.replaceState(null,'','?room='+identity.code);$('lobby').hidden=true;$('top').hidden=false;$('stage').hidden=false;$('game').src='/game';const stream=new EventSource('/api/events?room='+identity.code+'&id='+identity.id);stream.onmessage=e=>receive(JSON.parse(e.data));stream.onerror=()=>{connected=false;draw();configureFrame(undefined);error('连接中断，正在重连。')};stream.onopen=()=>error('');}catch(e){error(e.message);if(roomCode)sessionStorage.removeItem('world-trip-room-'+roomCode)}}
$('enter').onclick=enter;$('request').onclick=()=>api('request').catch(e=>error(e.message));$('seat').onchange=()=>api('seat',{seat:Number($('seat').value)}).catch(e=>{error(e.message);draw()});$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);error('链接已复制')}catch{prompt('复制这个房间链接',location.href)}};
async function flush(){if(posting||!queued||!connected||room?.controller!==identity.id)return;posting=true;const item=queued;queued=null;try{await api('snapshot',{snapshot:item.snapshot,epoch:item.epoch});}catch(e){error(e.message);if(room?.controller===identity.id&&item.epoch===room.epoch)queued=queued||item;setTimeout(()=>flush(),1000);return;}finally{posting=false;if(queued&&connected)setTimeout(()=>flush(),120)}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('game').contentWindow)return;const msg=e.data;if(msg.type==='game-ready'){frameReady=true;configureFrame(room?.snapshot)}if(msg.type==='game-snapshot'&&connected&&room?.controller===identity.id&&msg.epoch===room.epoch){queued={snapshot:msg.snapshot,epoch:msg.epoch};flush()}});
