
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{randomUUID,randomBytes}=require('node:crypto');
const BOARD=[{"id":0,"name":"起点","type":"start","price":0},{"id":1,"name":"美国","type":"land","price":3500,"build":2000},{"id":2,"name":"命运","type":"fate","price":0},{"id":3,"name":"加拿大","type":"land","price":3500,"build":2000},{"id":4,"name":"所得税","type":"tax","price":2000},{"id":5,"name":"纽约火车站","type":"station","price":2000},{"id":6,"name":"阿根廷","type":"land","price":1000,"build":500},{"id":7,"name":"机会","type":"chance","price":0},{"id":8,"name":"墨西哥","type":"land","price":1000,"build":500},{"id":9,"name":"古巴","type":"land","price":3000,"build":2000},{"id":10,"name":"坐牢 / 探监","type":"jail","price":0},{"id":11,"name":"法国","type":"land","price":3000,"build":2000},{"id":12,"name":"电力公司","type":"utility","price":1500},{"id":13,"name":"德国","type":"land","price":2400,"build":1500},{"id":14,"name":"意大利","type":"land","price":1400,"build":1000},{"id":15,"name":"巴黎火车站","type":"station","price":2000},{"id":16,"name":"西班牙","type":"land","price":1400,"build":1000},{"id":17,"name":"命运","type":"fate","price":0},{"id":18,"name":"希腊","type":"land","price":1600,"build":1000},{"id":19,"name":"荷兰","type":"land","price":2400,"build":1500},{"id":20,"name":"停车场","type":"park","price":0},{"id":21,"name":"英国","type":"land","price":2200,"build":1500},{"id":22,"name":"机会","type":"chance","price":0},{"id":23,"name":"俄罗斯","type":"land","price":1000,"build":500},{"id":24,"name":"泰国","type":"land","price":1800,"build":1000},{"id":25,"name":"东京火车站","type":"station","price":2000},{"id":26,"name":"土耳其","type":"land","price":3500,"build":2000},{"id":27,"name":"澳大利亚","type":"land","price":3200,"build":2000},{"id":28,"name":"自来水公司","type":"utility","price":1500},{"id":29,"name":"新加坡","type":"land","price":3000,"build":2000},{"id":30,"name":"进牢","type":"gojail","price":0},{"id":31,"name":"韩国","type":"land","price":1000,"build":500},{"id":32,"name":"中国","type":"land","price":4000,"build":2000},{"id":33,"name":"命运","type":"fate","price":0},{"id":34,"name":"中国香港","type":"land","price":2800,"build":1500},{"id":35,"name":"北京火车站","type":"station","price":2000},{"id":36,"name":"机会","type":"chance","price":0},{"id":37,"name":"日本","type":"land","price":1000,"build":500},{"id":38,"name":"财产税","type":"tax","price":1000},{"id":39,"name":"巴西","type":"land","price":1800,"build":1000}];
const rooms=new Map(),MAX_BODY=1024*1024;const root=__dirname;
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function view(room){return {code:room.code,revision:room.revision,epoch:room.epoch,host:room.host,controller:room.controller,snapshot:room.snapshot,events:room.events||[],financeVersion:room.financeVersion||0,started:!!room.started,requests:[...room.requests],members:[...room.members.values()].map(m=>({id:m.id,name:m.name,seat:m.seat,color:m.color,ready:!!m.ready,online:m.streams.size>0}))}}
function broadcast(room){room.updated=Date.now();const data='data: '+JSON.stringify(view(room))+'\n\n';for(const m of room.members.values())for(const res of m.streams)res.write(data)}
function handoff(room,id){if(room.controller===id)return;if(room.snapshot?.busy)throw Object.assign(Error('请等当前操作结束。'),{status:409});room.controller=id;room.epoch++;room.requests.delete(id)}
async function body(req){let size=0,parts=[];for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw Object.assign(Error('请求过大'),{status:413});parts.push(chunk)}return JSON.parse(Buffer.concat(parts).toString()||'{}')}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/health'){send(res,200,{ok:true,version:'online-own-role-20261007'});return}
if(req.method==='GET'&&['/','/client.js','/bridge.js','/game'].includes(url.pathname)){const file={'/':'index.html','/client.js':'client.js','/bridge.js':'bridge.js','/game':'game.html'}[url.pathname];let data=fs.readFileSync(path.join(root,file),'utf8');if(file==='game.html'){data=data.replace(/try\{const raw=localStorage\.getItem\(KEY\)[\s\S]*?catch\{setup\(\)\}/,'setup()');data=data.replace('</body>','<script src="/bridge.js"></script></body>')}
res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"frame-ancestors 'self'"});res.end(data);return}
if(!url.pathname.startsWith('/api/')){send(res,404,{error:'不存在'});return}
if(req.method==='POST'&&req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host){send(res,403,{error:'来源不匹配'});return}
if(req.method==='POST'&&url.pathname==='/api/create'){const data=await body(req);if(rooms.size>=200){send(res,503,{error:'房间已满'});return}const code=randomBytes(6).toString('hex'),id=randomUUID();const room={code,host:id,controller:id,epoch:1,revision:0,snapshot:null,stable:null,started:false,members:new Map(),requests:new Set(),updated:Date.now()};room.members.set(id,{id,name:String(data.name||'房主').slice(0,30),seat:0,color:'#3478ce',ready:false,streams:new Set()});rooms.set(code,room);send(res,200,{code,id});return}
const code=url.searchParams.get('room'),room=rooms.get(code);if(!room){send(res,404,{error:'房间不存在或已过期'});return}
if(req.method==='POST'&&url.pathname==='/api/join'){const data=await body(req);if(room.started){send(res,409,{error:'游戏已经开始，请创建新房间'});return}if(room.members.size>=4){send(res,409,{error:'房间人数已满'});return}const id=randomUUID(),used=new Set([...room.members.values()].map(m=>m.seat)),seat=[0,1,2,3].find(n=>!used.has(n));room.members.set(id,{id,name:String(data.name||'朋友').slice(0,30),seat:seat??null,color:['#3478ce','#d84b48','#e7bb35','#399560'].find(c=>![...room.members.values()].some(m=>m.color===c)),ready:false,streams:new Set()});send(res,200,{code,id});broadcast(room);return}
const id=url.searchParams.get('id'),member=room.members.get(id);if(!member){send(res,403,{error:'请重新加入房间'});return}
if(req.method==='POST'&&url.pathname==='/api/resume'){send(res,200,{ok:true});return}
if(req.method==='GET'&&url.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform',Connection:'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');member.streams.add(res);if(room.started&&!room.spin&&!room.snapshot?.busy&&room.snapshot?.actor===member.seat&&room.controller!==id)handoff(room,id);if(room.controller===id&&(room.spin||room.snapshot?.busy)&&member.streams.size===1&&room.stable){room.events??=[];room.events.push({id:randomUUID(),kind:'spin-cancel'});room.spin=null;room.snapshot=room.stable;room.revision++;room.epoch++;}broadcast(room);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),15000);req.on('close',()=>{clearInterval(heartbeat);member.streams.delete(res);broadcast(room)});return}
if(req.method!=='POST'){send(res,405,{error:'不支持的请求'});return}const data=await body(req);

if(url.pathname==='/api/action'){
 if(!room.started||!room.snapshot?.state)throw Error('游戏尚未开始');const st=room.snapshot.state,seat=member.seat,players=st.players;room.events??=[];room.financeVersion??=0;room.history??={};const key=(a,b)=>Math.min(a,b)+':'+Math.max(a,b);const copy=x=>JSON.parse(JSON.stringify(x));const emit=e=>{e.id=randomUUID();room.events.push(e);room.events=room.events.slice(-80);return e};
 if(data.kind==='spin'){const actor=st.phase==='contest'?st.contest.players[st.contest.results.length]:st.turn;if(actor!==seat||!['roll','contest'].includes(st.phase)||room.spin)throw Error('现在不能转盘');const value=1+require('node:crypto').randomInt(12);room.spin={who:seat,value};emit({kind:'spin',who:seat,value,startAngle:st.wheelAngle||0});send(res,200,{value});broadcast(room);return;}
 if(data.kind==='order'){if(!Array.isArray(data.order)||data.order.some(x=>st.props[x]?.owner!==seat)||new Set(data.order).size!==data.order.length)throw Error('无效地产顺序');players[seat].deedOrder=data.order;room.revision++;send(res,200,{ok:true});broadcast(room);return;}
 if(data.kind==='asset'){const i=data.tile,d=st.props[i],t=BOARD[i];if(!Number.isInteger(i)||!d||d.owner!==seat||players[seat].out||st.purchase||st.bankExchanges[seat]?.net||st.free?.lands?.includes(i))throw Error('现在不能管理这块地产');let amount,from,to,reason;if(data.sell){if(t.type!=='land'||!d.level)throw Error('没有可出售建筑');d.level--;amount=t.build/2;from=-1;to=seat;reason='出售'+t.name+'建筑';}else{if(d.level)throw Error('请先出售建筑');amount=t.price/2;if(d.mortgage){if(players[seat].cash<amount)throw Error('现金不足以赎回');from=seat;to=-1;reason='赎回'+t.name;}else{from=-1;to=seat;reason='抵押'+t.name;}d.mortgage=!d.mortgage;}const k=key(from,to),v=st.accounts[k]??={a:Math.min(from,to),b:Math.max(from,to),target:0,net:0,reasons:[]};v.target+=(from===v.a?1:-1)*amount;v.reasons.push(reason);st.notices.push({from,to,amount,paid:0,reason});room.financeVersion++;room.snapshot.financeVersion=room.financeVersion;room.revision++;room.stable=copy(room.snapshot);send(res,200,{snapshot:room.snapshot});broadcast(room);return;}
 const before=copy(room.snapshot);let from=data.from,to=data.to,d=data.d,undo=null;
 if(data.kind==='undo'){undo=room.history[seat]?.at(-1);if(!undo)throw Error('没有可撤回纸币');from=undo.to;to=undo.from;d=undo.d;}
 else if(data.kind!=='money')throw Error('未知操作');
 if(!Number.isInteger(from)||!Number.isInteger(to)||from===to||![10,50,100,200,500,1000,2000,5000].includes(d)||![from,to].includes(seat)||from < -1||to < -1||from>=players.length||to>=players.length)throw Error('无效收付款');
 if((from!==-1&&(players[from].out||!players[from].wallet[d]))||(to!==-1&&players[to].out))throw Error('没有这张纸币');
 st.accounts??={};st.giftBalances??={};st.bankExchanges??={};const v=st.accounts[key(from,to)],ex=st.bankExchanges[seat];const official=!!v&&v.target!==v.net&&!ex?.net;const giftKey=seat+':'+(from===seat?to:from);const gift=from!==-1&&to!==-1&&!official;
 if(!undo&&gift&&from!==seat&&(st.giftBalances[giftKey]||0)<d)throw Error('退回的金额不能超过已收到的赠与');
 if(!undo&&from===-1&&official){const delta=v.target-v.net,payer=delta>0?v.a:v.b;if(payer!==-1||d>Math.abs(delta))throw Error('银行只能支付应领取或找零的金额');}
 if(!undo&&from===-1&&!official&&!ex?.net)throw Error('银行尚未收到兑换纸币');
 if(!undo&&from===-1&&!official&&ex.net<d)throw Error('银行找零不能超过兑换余额');
 if(!undo&&official&&from!==seat&&from!==-1){const payer=(v.target>0?v.a:v.b);if(payer===from)throw Error('需要由付款玩家自己交钱');if(Math.abs(v.target-v.net)<d)throw Error('找零不能超过多付金额');}
 if(from!==-1){players[from].wallet[d]--;players[from].cash-=d}if(to!==-1){players[to].wallet[d]=(players[to].wallet[d]||0)+1;players[to].cash+=d}
 if(undo){if(undo.official){const book=st.accounts[undo.key];if(book)book.net-=(undo.from===book.a?1:-1)*d;}else if(undo.gift)st.giftBalances[undo.giftKey]-=(undo.from===seat?1:-1)*d;else {const bank=st.bankExchanges[seat]??={who:seat,net:0};bank.net-=(undo.from===seat?1:-1)*d;}if(st.purchase?.who===seat&&undo.purchase)st.purchase.paid-=(undo.from===seat?1:-1)*d;room.history[seat].pop();}
 else {if(official)v.net+=(from===v.a?1:-1)*d;else if(gift)st.giftBalances[giftKey]=(st.giftBalances[giftKey]||0)+(from===seat?d:-d);else {const bank=st.bankExchanges[seat]??={who:seat,net:0};bank.net+=(from===seat?d:-d);}const purchase=!!(st.purchase&&st.purchase.who===seat&&[from,to].includes(-1)&&official);if(purchase)st.purchase.paid+=(from===seat?d:-d);(room.history[seat]??=[]).push({from,to,d,official,gift,giftKey,key:key(from,to),purchase:purchase?copy(st.purchase):null});}
 for(const n of st.notices||[]){const book=st.accounts[key(n.from,n.to)];if(book){const delta=book.target-book.net;n.paid=delta===0?n.amount:Math.max(0,n.amount-Math.min(n.amount,Math.abs(delta)));}}
 st.onlineUndo=Object.fromEntries(Object.entries(room.history));room.financeVersion++;room.revision++;room.snapshot.financeVersion=room.financeVersion;room.snapshot.busy=false;room.stable=copy(room.snapshot);const event=emit({kind:'money',from,to,d,actor:seat,undo:!!undo,official,exchange:!official&&!gift});send(res,200,{before,snapshot:room.snapshot,event,financeVersion:room.financeVersion,undo:room.history[seat].at(-1)||null});broadcast(room);return;
}
if(url.pathname==='/api/profile'){if(room.started)throw Object.assign(Error('游戏已经开始'),{status:409});const name=String(data.name||'').trim().slice(0,16),color=data.color;if(!name||!['#3478ce','#d84b48','#e7bb35','#399560'].includes(color))throw Error('请选择名字和颜色');if(member.name!==name||member.color!==color)member.ready=false;member.name=name;member.color=color;if(typeof data.ready==='boolean')member.ready=data.ready;send(res,200,{ok:true});broadcast(room);return}
if(url.pathname==='/api/start'){if(id!==room.host)throw Object.assign(Error('只有房主可以开始'),{status:403});if(room.started)throw Object.assign(Error('游戏已经开始'),{status:409});const players=[...room.members.values()];if(players.length<2||players.some(m=>!m.ready||!m.streams.size))throw Object.assign(Error('请等待所有玩家在线并准备'),{status:409});if(new Set(players.map(m=>m.color)).size!==players.length)throw Object.assign(Error('颜色重复，请有人更换颜色后再开始'),{status:409});players.forEach((m,i)=>m.seat=i);room.started=true;room.controller=room.host;room.epoch++;send(res,200,{ok:true});broadcast(room);return}
if(url.pathname==='/api/snapshot'){if(!room.started)throw Object.assign(Error('请先在大厅准备并开始游戏'),{status:409});if(id!==room.controller||data.epoch!==room.epoch){send(res,409,{error:'操作权已交接'});return}if(!data.snapshot||typeof data.snapshot.busy!=='boolean'){send(res,400,{error:'无效状态'});return}if((data.snapshot.financeVersion||0)!==(room.financeVersion||0))throw Object.assign(Error('状态已更新，请重试'),{status:409});if(room.spin&&!data.snapshot.busy&&['walk','end','contest'].includes(data.snapshot.state?.phase)){const st=data.snapshot.state;if(st.phase==='walk'&&st.roll!==room.spin.value)throw Error('转盘结果不一致');room.events??=[];room.events.push({id:randomUUID(),kind:'spin-result',who:room.spin.who,value:room.spin.value});room.events=room.events.slice(-80);room.spin=null;}if(data.snapshot.resetHistory||room.snapshot?.state.turn!==data.snapshot.state?.turn){room.history={};data.snapshot.state.onlineUndo={};}if(room.snapshot?.state.purchase&&!data.snapshot.state.purchase){const seat=room.snapshot.state.purchase.who;room.history??={};room.history[seat]=(room.history[seat]||[]).filter(t=>!t.purchase);data.snapshot.state.onlineUndo??={};data.snapshot.state.onlineUndo[seat]=room.history[seat];}room.snapshot=data.snapshot;room.revision++;if(!data.snapshot.busy)room.stable=data.snapshot;
const seat=data.snapshot.actor,previous=room.lastActor;room.lastActor=seat;if(!data.snapshot.busy&&Number.isInteger(seat)&&seat!==previous){const next=[...room.members.values()].find(m=>m.seat===seat&&m.streams.size);if(next)handoff(room,next.id)}send(res,200,{revision:room.revision});broadcast(room);return}
if(url.pathname==='/api/request')throw Object.assign(Error('请求操作功能已移除'),{status:404});
if(url.pathname==='/api/handoff')throw Object.assign(Error('每位玩家只能操控自己的角色'),{status:403});
if(false){if(id!==room.controller&&id!==room.host){send(res,403,{error:'只有操作者或房主可以交接'});return}const target=room.members.get(data.target);if(!target||!target.streams.size){send(res,409,{error:'该玩家未在线'});return}if(id===room.host&&!room.members.get(room.controller)?.streams.size&&room.snapshot?.busy){room.snapshot=room.stable;room.revision++;}handoff(room,target.id);send(res,200,{ok:true});broadcast(room);return}
if(url.pathname==='/api/seat'){throw Object.assign(Error('角色由大厅确定'),{status:409});const seat=data.seat;if(!Number.isInteger(seat)||seat<0||seat>3||[...room.members.values()].some(m=>m.id!==id&&m.seat===seat)){send(res,409,{error:'这个玩家已有人选择'});return}member.seat=seat;send(res,200,{ok:true});broadcast(room);return}
send(res,404,{error:'不存在'});
}catch(e){if(!res.headersSent)send(res,e.status||400,{error:e.message||'请求失败'});else res.end()}});
setInterval(()=>{for(const [code,room]of rooms)if(Date.now()-room.updated>24*3600*1000&&![...room.members.values()].some(m=>m.streams.size))rooms.delete(code)},60000).unref();
server.listen(Number(process.env.PORT||8787),'0.0.0.0',()=>console.log('World Trip rooms ready on '+(process.env.PORT||8787)));
