
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{randomUUID,randomBytes}=require('node:crypto');
const rooms=new Map(),MAX_BODY=1024*1024;const root=__dirname;
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function view(room){return {code:room.code,revision:room.revision,epoch:room.epoch,host:room.host,controller:room.controller,snapshot:room.snapshot,requests:[...room.requests],members:[...room.members.values()].map(m=>({id:m.id,name:m.name,seat:m.seat,online:m.streams.size>0}))}}
function broadcast(room){room.updated=Date.now();const data='data: '+JSON.stringify(view(room))+'\n\n';for(const m of room.members.values())for(const res of m.streams)res.write(data)}
function handoff(room,id){if(room.controller===id)return;if(room.snapshot?.busy)throw Object.assign(Error('请等当前操作结束。'),{status:409});room.controller=id;room.epoch++;room.requests.delete(id)}
async function body(req){let size=0,parts=[];for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw Object.assign(Error('请求过大'),{status:413});parts.push(chunk)}return JSON.parse(Buffer.concat(parts).toString()||'{}')}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/health'){send(res,200,{ok:true});return}
if(req.method==='GET'&&['/','/client.js','/bridge.js','/game'].includes(url.pathname)){const file={'/':'index.html','/client.js':'client.js','/bridge.js':'bridge.js','/game':'game.html'}[url.pathname];let data=fs.readFileSync(path.join(root,file),'utf8');if(file==='game.html'){data=data.replace(/try\{const raw=localStorage\.getItem\(KEY\)[\s\S]*?catch\{setup\(\)\}/,'setup()');data=data.replace('</body>','<script src="/bridge.js"></script></body>')}
res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"frame-ancestors 'self'"});res.end(data);return}
if(!url.pathname.startsWith('/api/')){send(res,404,{error:'不存在'});return}
if(req.method==='POST'&&req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host){send(res,403,{error:'来源不匹配'});return}
if(req.method==='POST'&&url.pathname==='/api/create'){const data=await body(req);if(rooms.size>=200){send(res,503,{error:'房间已满'});return}const code=randomBytes(6).toString('hex'),id=randomUUID();const room={code,host:id,controller:id,epoch:1,revision:0,snapshot:null,stable:null,members:new Map(),requests:new Set(),updated:Date.now()};room.members.set(id,{id,name:String(data.name||'房主').slice(0,30),seat:0,streams:new Set()});rooms.set(code,room);send(res,200,{code,id});return}
const code=url.searchParams.get('room'),room=rooms.get(code);if(!room){send(res,404,{error:'房间不存在或已过期'});return}
if(req.method==='POST'&&url.pathname==='/api/join'){const data=await body(req);if(room.members.size>=12){send(res,409,{error:'房间人数已满'});return}const id=randomUUID(),used=new Set([...room.members.values()].map(m=>m.seat)),seat=[0,1,2,3].find(n=>!used.has(n));room.members.set(id,{id,name:String(data.name||'朋友').slice(0,30),seat:seat??null,streams:new Set()});send(res,200,{code,id});broadcast(room);return}
const id=url.searchParams.get('id'),member=room.members.get(id);if(!member){send(res,403,{error:'请重新加入房间'});return}
if(req.method==='GET'&&url.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform',Connection:'keep-alive','X-Accel-Buffering':'no'});res.write(': connected\n\n');member.streams.add(res);broadcast(room);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),15000);req.on('close',()=>{clearInterval(heartbeat);member.streams.delete(res);broadcast(room)});return}
if(req.method!=='POST'){send(res,405,{error:'不支持的请求'});return}const data=await body(req);
if(url.pathname==='/api/snapshot'){if(id!==room.controller||data.epoch!==room.epoch){send(res,409,{error:'操作权已交接'});return}if(!data.snapshot||typeof data.snapshot.busy!=='boolean'){send(res,400,{error:'无效状态'});return}room.snapshot=data.snapshot;room.revision++;if(!data.snapshot.busy)room.stable=data.snapshot;
const seat=data.snapshot.actor,previous=room.lastActor;room.lastActor=seat;if(!data.snapshot.busy&&Number.isInteger(seat)&&seat!==previous){const next=[...room.members.values()].find(m=>m.seat===seat&&m.streams.size);if(next)handoff(room,next.id)}send(res,200,{revision:room.revision});broadcast(room);return}
if(url.pathname==='/api/request'){room.requests.add(id);send(res,200,{ok:true});broadcast(room);return}
if(url.pathname==='/api/handoff'){if(id!==room.controller&&id!==room.host){send(res,403,{error:'只有操作者或房主可以交接'});return}const target=room.members.get(data.target);if(!target||!target.streams.size){send(res,409,{error:'该玩家未在线'});return}if(id===room.host&&!room.members.get(room.controller)?.streams.size&&room.snapshot?.busy){room.snapshot=room.stable;room.revision++;}handoff(room,target.id);send(res,200,{ok:true});broadcast(room);return}
if(url.pathname==='/api/seat'){const seat=data.seat;if(!Number.isInteger(seat)||seat<0||seat>3||[...room.members.values()].some(m=>m.id!==id&&m.seat===seat)){send(res,409,{error:'这个玩家已有人选择'});return}member.seat=seat;send(res,200,{ok:true});broadcast(room);return}
send(res,404,{error:'不存在'});
}catch(e){if(!res.headersSent)send(res,e.status||400,{error:e.message||'请求失败'});else res.end()}});
setInterval(()=>{for(const [code,room]of rooms)if(Date.now()-room.updated>24*3600*1000&&![...room.members.values()].some(m=>m.streams.size))rooms.delete(code)},60000).unref();
server.listen(Number(process.env.PORT||8787),'0.0.0.0',()=>console.log('World Trip rooms ready on '+(process.env.PORT||8787)));
